FROM            ubuntu:14.04

MAINTAINER      huiwq1990

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get -qq update && apt-get -qq -y install wget
RUN apt-get -qq install nasm
RUN apt-get -qq install binutils
RUN apt-get -qq install git