https://github.com/afaqurk/linux-dash/archive/1.5.zip

FROM centos:6.6

yum -y install gcc make gcc-c++ openssl-devel wget

wget http://nodejs.org/dist/v0.10.26/node-v0.10.26.tar.gz
tar -zvxf node-v0.10.26.tar.gz
#编译及安装
make && make install
#验证是否安装配置成功：
node -v


wget https://github.com/afaqurk/linux-dash/archive/1.5.tar.gz
tar -zvxf 1.5.tar.gz



